# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: openlineage-dbt
  version: "1.50.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OpenLineage/OpenLineage/archive/refs/tags/${{ version }}.tar.gz
  sha256: 393af02649095ff829dfc1f4193b61a6955cff1243facb8131429d6ec986096b

build:
  number: 0
  noarch: python
  script:
    - cd integration/dbt
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dbt-ol = openlineage.dbt:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.9.4,<0.10.0
  run:
    - python >=${{ python_min }},<4.0
    - tqdm >=4.62.0
    - openlineage-integration-common ==${{ version }}
    - dbt-core >=1.0.0

tests:
  - python:
      imports:
        - openlineage.dbt
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - dbt-core >=1.0.0
    script:
      # Note: Needs fix to enable script cli check dbt-ol --help
      # Error is │ FileNotFoundError: [Errno 2] No such file or directory: './dbt_project.yml'
      #- dbt-ol --help
      - pip check

about:
  summary: OpenLineage integration with dbt
  homepage: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-integration-common
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
